🔵 Notes to test

- mean serum protein and the beta-2 microglobulin decreased after treatment, whereas the serum albumin increased (p < 0.01)
- A Wilcoxon test was used to test the difference in textural features before and after treatment connected with -> To address the multiple comparisons, a Benjamin Hochberg correction was applied

In [22]:
import pandas as pd

🔵 Load clinical df

In [23]:
clinical_df = pd.read_csv(r"D:\Clinical_data\Table_clinical_data.csv", encoding="cp1252")
features_df = pd.read_csv(r"D:\CSV\merged_CaSupp_25_radiomics_spine_lesions_features.csv")

clinical_df.head()

,Patient ID,line of treatment,M-protein type,Light chain type,Serum M-protein quantity (g/l),Serum kappa FLC quantity (mg/l,Serum lambda FLC quantity (mg/l),IgG quantity (g/l),IgA quantity (g/l),IgM quantity (g/l),Plasmocyte count FC (%),Flow cytometry – circulating plasma cells (peripheral blood),Calcium total level (mmol/l),Creatinine level (µmol/l),Beta2 microglobulin (mg/l),ISS classification,Treatment regimen,Maximal response to treatment,MM associated amyloidosis,Follow - up
0,Myel_001,1st line,IgG,Kappa,21.4,143.00,9.25,32.87,1.59,0.82,0.86,NaN,2.37,81.0,2.02,Stage 1,bortezomib + lenalidomid + dexamethason,MR,no,NaN
1,Myel_002,1st line,IgA,Kappa,1.0,8870.00,2.10,1.90,0.73,0.05,12.00,NaN,2.44,51.0,4.71,Stage 2,bortezomib + cyklofosfamid + dexamethason,NaN,no,NaN
2,Myel_003,1st line,IgG,Kappa,1.1,287.00,7.46,6.66,0.87,0.28,6.50,yes,2.46,56.0,1.57,Stage 1,bortezomib + lenalidomid + dexamethason,VGPR,no,NaN
3,Myel_004,1st line,IgA,Kappa,0.0,1585.17,4.64,6.30,2.23,0.51,NaN,NaN,2.24,169.0,5.89,Stage 3,bortezomib + lenalidomid + dexamethason,VGPR,no,NaN
4,Myel_005,1st line,IgA,Lambda,14.8,23.40,1219.00,4.48,30.19,0.14,4.00,yes,2.22,189.0,15.75,Stage 3,bortezomib + lenalidomid + dexamethason,VGPR,no,NaN

🔵 Select df before and after treatment

In [24]:
before_patients = ["Myel_012", "Myel_018", "Myel_023", "Myel_043", "Myel_052"]
after_patients = ["Myel_069", "Myel_047", "Myel_024", "Myel_059", "Myel_070"]

clinical_features = ["Beta2 microglobulin (mg/l)", "Serum M-protein quantity (g/l)"]
image_features = ["n_lesions", "original_shape_VoxelVolume"]

features_before = features_df[features_df['patient'].isin(before_patients)][['patient'] + image_features]
clinical_before = clinical_df[clinical_df['Patient ID'].isin(before_patients)][['Patient ID'] + clinical_features]
data_before = pd.merge(clinical_before, features_before, left_on='Patient ID', right_on='patient', how='inner').drop(columns=['patient'])
data_before['Patient ID'] = pd.Categorical(data_before['Patient ID'], categories=before_patients, ordered=True)
data_before = data_before.sort_values('Patient ID').reset_index(drop=True)

features_after = features_df[features_df['patient'].isin(after_patients)][['patient'] + image_features]
clinical_after = clinical_df[clinical_df['Patient ID'].isin(after_patients)][['Patient ID'] + clinical_features]
data_after = pd.merge(clinical_after, features_after, left_on='Patient ID', right_on='patient', how='inner').drop(columns=['patient'])
data_after['Patient ID'] = pd.Categorical(data_after['Patient ID'], categories=after_patients, ordered=True)
data_after = data_after.sort_values('Patient ID').reset_index(drop=True)

In [25]:
data_before.head()

,Patient ID,Beta2 microglobulin (mg/l),Serum M-protein quantity (g/l),n_lesions,original_shape_VoxelVolume
0,Myel_012,2.90,51.7,32,8261.366404
1,Myel_018,8.21,23.4,25,12251.587393
2,Myel_023,1.60,5.7,40,11243.205191
3,Myel_043,3.47,0.0,132,52914.638340
4,Myel_052,NaN,NaN,76,15433.015057

In [26]:
data_after.head()

,Patient ID,Beta2 microglobulin (mg/l),Serum M-protein quantity (g/l),n_lesions,original_shape_VoxelVolume
0,Myel_069,1.93,27.4,22,3881.435474
1,Myel_047,8.21,23.4,59,32553.118763
2,Myel_024,1.85,0.0,41,13523.156138
3,Myel_059,2.90,0.0,90,61543.580812
4,Myel_070,NaN,NaN,93,29901.169145

🔵 mean serum protein and the beta-2 microglobulin decreased after treatment, whereas the serum albumin increased (p < 0.01)