In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu

In [14]:
c25_l = pd.read_csv(r"D:\CSV\merged_CaSupp_25_radiomics_spine_lesions_features.csv")
vmi40_l = pd.read_csv(r"D:\CSV\merged_monoe_40kev_radiomics_spine_lesions_features.csv")
vmi80_l = pd.read_csv(r"D:\CSV\merged_monoe_80kev_radiomics_spine_lesions_features.csv")
vmi120_l = pd.read_csv(r"D:\CSV\merged_monoe_120kev_radiomics_spine_lesions_features.csv")
konv_l = pd.read_csv(r"D:\CSV\merged_konv_radiomics_spine_lesions_features.csv")

print(c25_l.shape == konv_l.shape == vmi40_l.shape == vmi80_l.shape == vmi120_l.shape)
konv_l.head()

True

,patient,n_lesions,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,...,gradient_gldm_LargeDependenceLowGrayLevelEmphasis,gradient_gldm_LowGrayLevelEmphasis,gradient_gldm_SmallDependenceEmphasis,gradient_gldm_SmallDependenceHighGrayLevelEmphasis,gradient_gldm_SmallDependenceLowGrayLevelEmphasis,gradient_ngtdm_Busyness,gradient_ngtdm_Coarseness,gradient_ngtdm_Complexity,gradient_ngtdm_Contrast,gradient_ngtdm_Strength
0,Myel_001,42,0.208989,0.090847,48.159211,530.112286,489.628282,477.609470,70.013470,524.164765,...,6.122732,0.157440,0.184319,8.505441,0.023410,5.889803,0.001018,716.570846,0.016228,1.458824
1,Myel_002,26,0.312599,0.177995,56.369710,316.692125,312.249080,221.602910,62.017486,350.835395,...,15.394581,0.228428,0.113603,3.276586,0.019650,36.664949,0.000420,145.212907,0.020619,0.117901
2,Myel_003,8,0.212993,0.151570,36.779577,242.656717,119.996801,223.869005,26.654969,272.417997,...,8.686312,0.189166,0.140076,5.373117,0.021242,3.503891,0.003300,267.380807,0.024304,2.146824
3,Myel_004,54,0.159400,0.086384,43.732812,506.259109,448.915430,452.701719,83.059497,506.152358,...,20.037371,0.248563,0.139770,6.002010,0.019143,64.964842,0.000126,526.946978,0.014965,0.160763
4,Myel_005,12,0.192710,0.149551,57.235029,382.711335,214.831665,320.170141,47.350217,373.626743,...,5.086489,0.125267,0.163024,7.552599,0.022552,8.455277,0.001020,346.389725,0.028856,0.486303

In [15]:
c25_v = pd.read_csv(r"D:\CSV\merged_CaSupp_25_radiomics_spine_vertebrae_features.csv")
vmi40_v = pd.read_csv(r"D:\CSV\merged_monoe_40kev_radiomics_spine_vertebrae_features.csv")
vmi80_v = pd.read_csv(r"D:\CSV\merged_monoe_80kev_radiomics_spine_vertebrae_features.csv")
vmi120_v = pd.read_csv(r"D:\CSV\merged_monoe_120kev_radiomics_spine_vertebrae_features.csv")
konv_v = pd.read_csv(r"D:\CSV\merged_konv_radiomics_spine_vertebrae_features.csv")

print(c25_v.shape == konv_v.shape == vmi40_v.shape == vmi80_v.shape == vmi120_v.shape)
konv_v.head()

True

,patient,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,gradient_gldm_LargeDependenceLowGrayLevelEmphasis,gradient_gldm_LowGrayLevelEmphasis,gradient_gldm_SmallDependenceEmphasis,gradient_gldm_SmallDependenceHighGrayLevelEmphasis,gradient_gldm_SmallDependenceLowGrayLevelEmphasis,gradient_ngtdm_Busyness,gradient_ngtdm_Coarseness,gradient_ngtdm_Complexity,gradient_ngtdm_Contrast,gradient_ngtdm_Strength
0,Myel_001,0.195901,0.091161,62.188608,682.187701,611.932129,619.461261,102.706337,619.628277,998881.738915,...,4.356938,0.080232,0.234340,70.820623,0.012127,131.106008,0.000005,30647.495479,0.023025,0.220660
1,Myel_002,0.279675,0.141591,60.476069,427.119208,369.384496,385.671669,218.359462,389.540681,668375.464466,...,10.267083,0.123325,0.164645,25.079424,0.011264,421.969119,0.000007,2076.729435,0.055271,0.017388
2,Myel_003,0.169913,0.089999,53.678508,596.436470,533.220116,532.065109,87.700532,534.805317,649570.392328,...,6.446598,0.094709,0.251062,68.740456,0.011193,308.588594,0.000007,4545.574022,0.125424,0.020566
3,Myel_004,0.160987,0.094363,55.947434,592.895940,517.532196,531.045330,113.285459,533.728207,726050.764625,...,6.568184,0.102001,0.203709,35.966546,0.012739,357.837378,0.000006,3617.872103,0.058069,0.022710
4,Myel_005,0.227423,0.105056,58.541502,557.239603,508.240551,506.337593,96.973136,508.898768,799606.140136,...,3.174115,0.073690,0.212420,42.769538,0.012807,438.920734,0.000005,3552.919211,0.073349,0.015886

In [ ]:
df1, df2 = c25_l, c25_v

common_features = df1.select_dtypes(include=['float64', 'int64']).columns.intersection(df2.select_dtypes(include=['float64', 'int64']).columns)

for feature in common_features:
    if "shape" in feature:
        continue

    data = pd.DataFrame({
        feature: pd.concat([df1[feature], df2[feature]], ignore_index=True),
        'Dataset': ['Lesions df']*len(df1) + ['Vertebrae df']*len(df2)
    }).dropna()

    plt.figure(figsize=(6,4))
    sns.boxplot(x='Dataset', y=feature, data=data, hue='Dataset', palette=['skyblue', 'salmon'], dodge=False, legend=False)
    plt.title(f'Comparison: {feature}')
    plt.ylabel(feature)
    plt.show()

In [ ]:
pairs = [(c25_l, c25_v), (vmi40_l, vmi40_v), (vmi80_l, vmi80_v), (vmi120_l, vmi120_v), (konv_l, konv_v)]
names = [("c25_l", "c25_v"), ("vmi40_l", "vmi40_v"), ("vmi80_l", "vmi80_v"), ("vmi120_l", "vmi120_v"), ("konv_l", "konv_v")]

common_features = set(pairs[0][0].select_dtypes(include=['float64','int64']).columns) & set(pairs[0][1].select_dtypes(include=['float64','int64']).columns)
for df_a, df_b in pairs[1:]:
    cols_a = set(df_a.select_dtypes(include=['float64','int64']).columns)
    cols_b = set(df_b.select_dtypes(include=['float64','int64']).columns)
    common_features &= cols_a & cols_b

for feature in common_features:
    if "shape" in feature:
        continue

    data_list = []
    for i, ((df_a, df_b), (name_a, name_b)) in enumerate(zip(pairs, names), start=1):

        temp_a = pd.DataFrame({
        'Feature': df_a[feature],
        'Dataset': name_a
        })
        temp_b = pd.DataFrame({
            'Feature': df_b[feature],
            'Dataset': name_b
        })

        data_list.append(temp_a)
        data_list.append(temp_b)

    data_all = pd.concat(data_list).dropna()

    plt.figure(figsize=(12,5))
    sns.boxplot(x='Dataset', y='Feature', data=data_all, hue='Dataset', palette='tab10', dodge=False, legend=False)
    plt.title(f'Compare: {feature} through all dfs')
    plt.ylabel(feature)
    plt.xticks(rotation=45)
    plt.show()

In [25]:
df1, df2 = konv_l, konv_v

common_features = df1.select_dtypes(include=['float64','int64']).columns.intersection(df2.select_dtypes(include=['float64','int64']).columns)

results = {}

for feature in common_features:
    if "shape" in feature:
        continue
    group1 = df1[feature].dropna()
    group2 = df2[feature].dropna()

    u_stat, p_value = mannwhitneyu(group1, group2, alternative='two-sided')
    results[feature] = {'U_stat': u_stat, 'p_value': p_value}

t_test_df = pd.DataFrame(results).T
significant_features = t_test_df[t_test_df['p_value'] < 0.05].sort_values('p_value')

print("Štatisticky významné rozdiely podľa Mann-Whitney U testu:")
print(significant_features)

Štatisticky významné rozdiely podľa Mann-Whitney U testu:
                                        U_stat       p_value
original_firstorder_InterquartileRange     0.0  3.948503e-25
original_firstorder_Maximum                0.0  3.975214e-25
original_firstorder_Median                 0.0  3.978673e-25
original_firstorder_90Percentile           0.0  3.980837e-25
original_firstorder_Range                  0.0  3.988201e-25
...                                        ...           ...
gradient_glcm_Idmn                      3450.0  6.121687e-04
gradient_glszm_SmallAreaEmphasis        1770.0  1.029546e-03
original_ngtdm_Strength                 3414.0  1.029546e-03
original_glszm_ZoneVariance             1998.0  1.772345e-02
original_glszm_LargeAreaEmphasis        2034.0  2.591344e-02

[185 rows x 2 columns]